package com.accuragroup.eg.Vir.models.Entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPARE_PRODUCT".
*/
public class CompareProductDao extends AbstractDao<CompareProduct, Long> {

    public static final String TABLENAME = "COMPARE_PRODUCT";

    /**
     * Properties of entity CompareProduct.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Img = new Property(1, String.class, "img", false, "IMG");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Price = new Property(3, int.class, "price", false, "PRICE");
        public final static Property Description = new Property(4, String.class, "description", false, "DESCRIPTION");
        public final static Property Owner = new Property(5, String.class, "owner", false, "OWNER");
        public final static Property City = new Property(6, String.class, "city", false, "CITY");
        public final static Property Gov = new Property(7, String.class, "gov", false, "GOV");
        public final static Property Rate = new Property(8, int.class, "rate", false, "RATE");
        public final static Property Reserved = new Property(9, int.class, "reserved", false, "RESERVED");
    }


    public CompareProductDao(DaoConfig config) {
        super(config);
    }
    
    public CompareProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPARE_PRODUCT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"IMG\" TEXT," + // 1: img
                "\"TITLE\" TEXT," + // 2: title
                "\"PRICE\" INTEGER NOT NULL ," + // 3: price
                "\"DESCRIPTION\" TEXT," + // 4: description
                "\"OWNER\" TEXT," + // 5: owner
                "\"CITY\" TEXT," + // 6: city
                "\"GOV\" TEXT," + // 7: gov
                "\"RATE\" INTEGER NOT NULL ," + // 8: rate
                "\"RESERVED\" INTEGER NOT NULL );"); // 9: reserved
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPARE_PRODUCT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompareProduct entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getPrice());
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(5, description);
        }
 
        String owner = entity.getOwner();
        if (owner != null) {
            stmt.bindString(6, owner);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(7, city);
        }
 
        String gov = entity.getGov();
        if (gov != null) {
            stmt.bindString(8, gov);
        }
        stmt.bindLong(9, entity.getRate());
        stmt.bindLong(10, entity.getReserved());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompareProduct entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getPrice());
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(5, description);
        }
 
        String owner = entity.getOwner();
        if (owner != null) {
            stmt.bindString(6, owner);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(7, city);
        }
 
        String gov = entity.getGov();
        if (gov != null) {
            stmt.bindString(8, gov);
        }
        stmt.bindLong(9, entity.getRate());
        stmt.bindLong(10, entity.getReserved());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public CompareProduct readEntity(Cursor cursor, int offset) {
        CompareProduct entity = new CompareProduct( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // img
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.getInt(offset + 3), // price
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // description
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // owner
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // city
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // gov
            cursor.getInt(offset + 8), // rate
            cursor.getInt(offset + 9) // reserved
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompareProduct entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setImg(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPrice(cursor.getInt(offset + 3));
        entity.setDescription(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOwner(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCity(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setGov(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setRate(cursor.getInt(offset + 8));
        entity.setReserved(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompareProduct entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompareProduct entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompareProduct entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
