package com.accuragroup.eg.Vir.models.Entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.accuragroup.eg.Vir.models.Entities.CartProducts;
import com.accuragroup.eg.Vir.models.Entities.CompareProduct;
import com.accuragroup.eg.Vir.models.Entities.FavouritProduct;

import com.accuragroup.eg.Vir.models.Entities.CartProductsDao;
import com.accuragroup.eg.Vir.models.Entities.CompareProductDao;
import com.accuragroup.eg.Vir.models.Entities.FavouritProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartProductsDaoConfig;
    private final DaoConfig compareProductDaoConfig;
    private final DaoConfig favouritProductDaoConfig;

    private final CartProductsDao cartProductsDao;
    private final CompareProductDao compareProductDao;
    private final FavouritProductDao favouritProductDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartProductsDaoConfig = daoConfigMap.get(CartProductsDao.class).clone();
        cartProductsDaoConfig.initIdentityScope(type);

        compareProductDaoConfig = daoConfigMap.get(CompareProductDao.class).clone();
        compareProductDaoConfig.initIdentityScope(type);

        favouritProductDaoConfig = daoConfigMap.get(FavouritProductDao.class).clone();
        favouritProductDaoConfig.initIdentityScope(type);

        cartProductsDao = new CartProductsDao(cartProductsDaoConfig, this);
        compareProductDao = new CompareProductDao(compareProductDaoConfig, this);
        favouritProductDao = new FavouritProductDao(favouritProductDaoConfig, this);

        registerDao(CartProducts.class, cartProductsDao);
        registerDao(CompareProduct.class, compareProductDao);
        registerDao(FavouritProduct.class, favouritProductDao);
    }
    
    public void clear() {
        cartProductsDaoConfig.clearIdentityScope();
        compareProductDaoConfig.clearIdentityScope();
        favouritProductDaoConfig.clearIdentityScope();
    }

    public CartProductsDao getCartProductsDao() {
        return cartProductsDao;
    }

    public CompareProductDao getCompareProductDao() {
        return compareProductDao;
    }

    public FavouritProductDao getFavouritProductDao() {
        return favouritProductDao;
    }

}
